# Generated by Django 5.0.6 on 2024-05-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=256)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
